name: Build and Test CLI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version:  3.8

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Set up Pipenv and install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Run tests with coverage
      run: |
        pipenv run coverage run --source=./src -m pytest
        pipenv run coverage report -m

    - name: Generate coverage badge
      uses: tj-actions/coverage-badge-py@v2

    - name: Commit coverage badge
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add coverage.svg
        git commit -m "Update coverage badge" || echo "No changes to commit"
        git push